### ISSUE TITLE
Error: Cannot find module './lib/parse-js' from uglify-js.js

### ISSUE THREAD

**Issue by davisford** [socketstream/socketstream#218]
I have a socketstream app I started using the demo app builder on Mac.  Now I'm trying to document dev. environment setup on an Ubuntu box and run my app.  The app runs fine on Mac OS, but after I've installed node, npm, socketstream (as per Install.md) and all the other dependencies I'm using I get this when I try to run my app:

```
root@kafka:/home/davis/git/daisycentral# node app.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module './lib/parse-js'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/davis/git/socketstream/node_modules/uglify-js/uglify-js.js:14:17)

```

The line in question:

```
uglify.parser = require("./lib/parse-js");
```

Seems like a path went wrong somewhere, but it isn't clear to me.  Any ideas?

**Comment by MaheshBusa** [comment]
module.js:471
    throw err;
    ^

Error: Cannot find module './lib/parse-js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\nabusa\project\angular-seed-enhanced-master\
node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_mod
ules\uglify-js\uglify-js.js:14:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
