### ISSUE TITLE
Bug: quick-test npm task fails

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#573]
See stacktrace:

  1) pack "after each" hook:
     Error: Command failed: /bin/sh -c cd /Users/pauljensen/Work/socketstream/socketstream/test/fixtures && git checkout project/client/static/assets
fatal: Not a git repository: '.git'

      at ChildProcess.exithandler (child_process.js:197:12)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:764:16)
      at Socket.<anonymous> (internal/child_process.js:319:11)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at Pipe._onclose (net.js:469:12)

**Comment by thepian** [comment]
For me it passes, but when run in a commit hook in Tower it fails due to colors being output. Some test needs a logHook to catch the build dump

**Comment by thepian** [comment]
ah you mean if you run it as a download, not a git repo?

**Comment by thepian** [comment]
removed the git checkout
