### ISSUE TITLE
existsSync no longer exists on Node 6

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream#607]
```
/Users/pauljensen/Work/anephenix/anephenix/node_modules/socketstream/lib/request/middleware/index.js:27
      stack = existslib.existsSync(customDir) && apiTree.createApiTree(customDir) || {};
                        ^

TypeError: existslib.existsSync is not a function
    at Object.load (/Users/pauljensen/Work/anephenix/anephenix/node_modules/socketstream/lib/request/middleware/index.js:27:25)
    at Object.load (/Users/pauljensen/Work/anephenix/anephenix/node_modules/socketstream/lib/request/index.js:51:36)
    at start (/Users/pauljensen/Work/anephenix/anephenix/node_modules/socketstream/lib/socketstream.js:85:35)
    at Object.exports.start (/Users/pauljensen/Work/anephenix/anephenix/node_modules/socketstream/lib/socketstream.js:138:46)
    at Object.<anonymous> (/Users/pauljensen/Work/anephenix/anephenix/app.js:52:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by paulbjensen** [comment]
I'm going to see if I can fix this first, before changing anything else.

**Comment by paulbjensen** [comment]
I should add that this was run on an app running 0.3.

**Comment by paulbjensen** [comment]
I'll note that 0.3 doesn't work on Node 6. As for 0.4.5, chokidar@1.1.0 is not installing on Node 6:

```
socketstream socketstream new test-app
module.js:471
    throw err;
    ^

Error: Cannot find module 'chokidar'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pauljensen/.nvm/versions/node/v6.9.1/lib/node_modules/socketstream/lib/tasks/live_reload.js:9:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by paulbjensen** [comment]
Going to close - SocketStream 0.3 won't be supported on Node.js version 6.
