### ISSUE TITLE
Error: Cannot find module './lib/parse-js'

### ISSUE THREAD

**Issue by MaheshBusa** [socketstream/socketstream#616]
module.js:471
    throw err;
    ^

Error: Cannot find module './lib/parse-js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\nabusa\project\angular-seed-enhanced-master\
node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_mod
ules\uglify-js\uglify-js.js:14:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by MaheshBusa** [comment]
[‎08-‎Feb-‎17 14:51] Busa, Naga: 
module.js:471 
module.js:471
    throw err;
    ^

Error: Cannot find module './lib/parse-js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\nabusa\project\angular-seed-enhanced-master\
node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_mod
ules\uglify-js\uglify-js.js:14:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by paulbjensen** [comment]
Hi,

As suggested in #218, try running this command to resolve the uglify-js issue that you are experiencing:

    npm install uglify-js -g

The stack trace indicates that this isn't running a SocketStream app, but instead another app, and therefore not directly-linked to SocketStream. I will therefore close this issue.
